!
! TWO-REACTION TEST CASE
! ZDPLASKIN
!
! This test case corresponds to an Ar plasma consisting of electrons, atomic
! ions, and neutrals. The charged particles are supposed to be generated by
! direct electron impact ionization and lost by 3-body recombination.
!
! June 2008, by S Pancheshnyi
!

program main
!
! declare variables and modules
!
  use ZDPlasKin
  implicit none
  double precision, parameter :: gas_temperature  = 300.0d0, & ! gas temperature, K
                                 reduced_field    = 50.0d0,  & ! reduced electric field, Td
                                 density_ini_ar   = 2.414d19,  & ! initial Ar density, cm-3
                                 density_ini_elec = 1.0d0      ! initial electron density, cm-3
  double precision            :: time  = 0.0d0, time_end = 2.2d-7, dtime = 1.0d-9 ! times, s
  integer                     :: i, t_iter, Nsteps, ifile_unit
  double precision, allocatable, dimension(:,:) :: outputData
  double precision :: rates(1:reactions_max)
!
! print
!
  write(*,'(/,A)') 'TWO-REACTION TEST CASE'
!
! initialization of ZDPlasKin
!
  call ZDPlasKin_init()

  Nsteps = int((time_end - time)/dtime)
! set the physical conditions of the calculation:
!     the gas temperature and the reduced electric field
!
  call ZDPlasKin_set_conditions(GAS_TEMPERATURE=gas_temperature,REDUCED_FIELD=reduced_field )
!
! set initial densities
!
  call ZDPlasKin_set_density(  'Ar',density_ini_ar)
  call ZDPlasKin_set_density(   'e',density_ini_elec)
  call ZDPlasKin_set_density('Ar^+',density_ini_elec)
! print column headers and initial values
!
  write(*,'(4(A12))') 'Time_s', ( trim(species_name(i)), i = 1, species_max )
  write(*,'(4(1pe12.4))') time, density(:)
!
! time integration
  t_iter = 0
  do while(time .lt. time_end)
    call ZDPlasKin_timestep(time,dtime)
    time = time + dtime
    call ZDPlaskin_write_qtplaskin(time)
    !write(*,'(4(1pe12.4))') time, density(:)
    call ZDPlasKin_get_rates(reaction_rates=rates(1:reactions_max))

    !write(*,'(3(1pe12.4))') time, rates(1)/(density(1)*density_ini_ar), rates(2)/(density(1)*density(3)*density(2))
    write(*,'(3(1pe12.4))') time, rates(1)/density(1), rates(2)/(density(1)*density(3))
    t_iter = t_iter+1
    enddo

end program main
