!
! TWO-REACTION TEST CASE
! ZDPLASKIN
!
! This test case corresponds to an Ar plasma consisting of electrons, atomic
! ions, and neutrals. The charged particles are supposed to be generated by
! direct electron impact ionization and lost by 3-body recombination.
!
! June 2008, by S Pancheshnyi
!

program twoWay
!
! declare variables and modules
!
  use ZDPlasKin
  implicit none
  !double precision, parameter :: gas_temperature  = 300.0d0, & ! gas temperature, K
  !                               reduced_field    = 50.0d0,  & ! reduced electric field, Td
  !                              density_ini_ar   = 2.5d19,  & ! initial Ar density, cm-3
  !                               density_ini_elec = 1.0d0      ! initial electron density, cm-3
  double precision, parameter :: initDensityX1 = 1.0d-1, &
                                 initDensityX2 = 9.0d-1
  double precision            :: time  = 0.0d0, time_end = 1.0d0, dtime = 1.0d-6 ! times, s
  integer                     :: i, t_iter, Nsteps, ifile_unit
  write(*,'(/,A)') 'Two way chemical reaction'
!
! initialization of ZDPlasKin
!
  call ZDPlasKin_init()

  Nsteps = int((time_end - time)/dtime)
  !allocate(outputData(species_max+1, Nsteps))
! set the physical conditions of the calculation:
!     the gas temperature and the reduced electric field
!
  !call ZDPlasKin_set_conditions(GAS_TEMPERATURE=gas_temperature,REDUCED_FIELD=reduced_field )
!
! set initial densities
!
  call ZDPlasKin_set_density(  'X1',initDensityX1) 
  call ZDPlasKin_set_density(  'X2',initDensityX2)
  !call ZDPlasKin_set_density('Ar^+',density_ini_elec)
! print column headers and initial values
!
  write(*,'(4(A12))') 'Time_s', ( trim(species_name(i)), i = 1, species_max )
  write(*,'(4(1pe12.4))') time, density(:)
!
! time integration
! Hema- I can modify it so that the output is actually written out to a file
  t_iter = 0
  do while(time .lt. time_end)
    call ZDPlasKin_timestep(time,dtime)
    time = time + dtime
    call ZDPlaskin_write_qtplaskin(time)
    write(*,'(4(1pe12.4))') time, density(:)
    t_iter = t_iter+1
    !outputData(1,t_iter) = time
    !outputData(2:, t_iter) = density(:)
    enddo

  !open(ifile_unit, file='outputData.txt', action='write')
  !write(ifile_unit,'(4(A12))') 'Time_s', ( trim(species_name(i)), i = 1, species_max ) 
  !do i=1,Nsteps
  !      write(ifile_unit, '(4(1pe12.4))') outputData(:, i)
  !end do
  !close(ifile_unit)

! end

end program twoWay
